robot_base_frame: base_footprint
update_frequency:
publish_frequency: 1.0
inflation_radius: 1.0

# publish_voxel_map: true
#
# map_type: voxel
# origin_z: 0.0
# z_resolution: 0.2
# z_voxels: 10
# unknown_threshold: 10
# mark_threshold: 0

observation_sources: hokuyo_scan velodyne_cloud #velodyne_scan # Don't have both velodyne scan and velodyne cloud.
hokuyo_scan: {data_type: LaserScan, topic: nav_hokuyo/scan, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.75, raytrace_range: 4.0} #raytrace_range must be less than max range of sensor.
velodyne_cloud: {data_type: PointCloud2, topic: velodyne/points_filtered, marking: true, clearing: true, obstacle_range: 3.75, raytrace_range: 4.00, max_obstacle_height: 1.5, min_obstacle_height: 0.1} #raytrace_range must be less than max range of sensor.
#velodyne_scan: {data_type: PointCloud2, topic: velodyne/scan_filtered, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 3.75, raytrace_range: 4.00} #raytrace_range must be less than max range of sensor.
